version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: library_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root  # Senha do usuário root
      MYSQL_DATABASE: library_db # Nome do banco que será criado
    ports:
      - "3307:3306"              # Porta Externa : Porta Interna
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: